version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/favorites.json:/app/favorites.json
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3000/api}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped 